### Correct trip start

POST http://localhost:5000/trip/start
Content-Type: application/json

{
  "name": "My first bike adventure",
  "user_id": 123
}

### /trip/start wrong parameters

POST http://localhost:5000/trip/start
Content-Type: application/json

{
  "name": "Correct parameter",
  "user": "Incorrect"
}

