version: '3.9'

services:
  backend:
    image: backend-app
    ports:
      - "80:80"
    build: backend
    depends_on:
      - postgres
    networks:
      - db_net

  postgres:
    image: postgres:13
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=s3cr3t
      - POSTGRES_DB=data_db
    networks:
      - db_net

networks:
  db_net:
    name: shared-db-net

volumes:
  postgres_data: