"""added trip and sensor tables

Revision ID: c0a3944210f4
Revises: 0f9863c11eea
Create Date: 2023-10-18 17:51:31.991383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a3944210f4'
down_revision = '0f9863c11eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_start'), ['start'], unique=False)

    op.create_table('gps',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_table('imu',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('acceleration_x', sa.Float(), nullable=True),
    sa.Column('acceleration_y', sa.Float(), nullable=True),
    sa.Column('acceleration_z', sa.Float(), nullable=True),
    sa.Column('gyroscope_x', sa.Float(), nullable=True),
    sa.Column('gyroscope_y', sa.Float(), nullable=True),
    sa.Column('gyroscope_z', sa.Float(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_table('vibration',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vibration')
    op.drop_table('imu')
    op.drop_table('gps')
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_start'))

    op.drop_table('trip')
    # ### end Alembic commands ###
